### ISSUE TITLE
Does not find all of my sound cards

### ISSUE THREAD

**Issue by pallaswept** [rncbc/rtirq#17]
Hi, and thanks for a great tool.

I attempted to use this and had the 'snd' entry in my conf file to prioritise. Accordingly, the script gets to [this line](https://github.com/pallaswept/rtirq/blob/d7acf3483e14af8f58ef98a1b09fa98952474bbc/rtirq.sh#L265C4-L265C31) and tries to grep  `/proc/asound/cards` for the string irq... but that won't work here. For some reason, only one of them actually shows it:

```
cat /proc/asound/cards
 0 [NVidia         ]: HDA-Intel - HDA NVidia
                      HDA NVidia at 0xfc080000 irq 97
 1 [Generic        ]: HDA-Intel - HD-Audio Generic
                      HDAudio-Gigabyte-ALC1220DualCodecs
 2 [Device         ]: USB-Audio - USB PnP Sound Device
                      C-Media Electronics Inc. USB PnP Sound Device at usb-0000:02:00.0-9.1.1, full s
 3 [Camera         ]: USB-Audio - USB Camera
                      USB Camera USB Camera at usb-0000:02:00.0-9.1.4, high speed
```

So, it doesn't work. The result is as follows (trimmed for easy reading):

```
> sudo rtirq status

  PID CLS RTPRIO  NI PRI %CPU STAT COMMAND
  263 FF      88   - 128  0.0 S    irq/8-rtc0
 4740 FF      86   - 126  0.0 S    irq/97-snd_hda_intel:card0
  852 FF      82   - 122  1.0 S    irq/94-nvidia

... etc, all the others, and then near the bottom....
  
 4766 FF      50   -  90  0.0 S    irq/98-snd_hda_intel:card1
...
```

For now, I've replaced the 'snd' entry in my conf file with 'snd_hda_intel' and that takes care of both of the top two cards:
```
> sudo rtirq status

  PID CLS RTPRIO  NI PRI %CPU STAT COMMAND
  263 FF      88   - 128  0.0 S    irq/8-rtc0
 4740 FF      86   - 126  0.0 S    irq/97-snd_hda_intel:card0
 4766 FF      85   - 125  0.0 S    irq/98-snd_hda_intel:card1
 ...etc...
 
```
... and the others are USB so the existing 'usb' entry takes care of them, so I have a functional workaround... but I get the impression this is not intended behaviour, and that you were expecting to see the IRQ of both of those first two cards. in the output of `/proc/asound/cards`

Thanks for any help with this!

**Comment by rncbc** [comment]
it is fine, the may and ought to tweak the `RTIRQ_NAME_LIST` rtirq.conf setting to your specific special needs.

**Comment by pallaswept** [comment]
No problem then, I have done just that, it works fine. If this is intended behaviour then I will go ahead and close this issue. Thanks for your help!
