### ISSUE TITLE
rtirq resets an irq after suspend

### ISSUE THREAD

**Issue by terencode** [rncbc/rtirq#3]
Here is my *RTIRQ_NAME_LIST*:  `"rtc 3670016-edge"`
Each time I suspend the computer, the first irq remains at the correct priority (-91) but the second one is set to *RTIRQ_PRIO_LOW* and I have to run rtirq service again for it to be set to its correct priority.

Archlinux 4.19.13-lqx

**Comment by rncbc** [comment]
maybe you ought to run `rtirq restart` on every suspend wake up?

if you have some kind of systemd wisardry for just that please make a pull-request here.

btw. `rtc` is dang moot and numb since a decade ago--you may remove it already from RTIRQ_NAME_LIST, if you care.

cheers

**Comment by terencode** [comment]
Thanks for your fast answer.
I did think about that and just figured out the right spell to do it, I'll submit the PR in a few minutes.

I didn't know about `rtc`, I never stumbled upon any resources talking about its deprecation. Do you know where I can learn more about it (and what is used now) ?

**Comment by rncbc** [comment]
rtc was instrumental long ago in the early time of the preempt_rt kernel patch, a time where rtirq was raised; those were very early primordial times (decade+ ago), you don't have to remember the hell back then ;)

**Comment by terencode** [comment]
Ok then ^^
I opened #4 which is not working yet.

**Comment by terencode** [comment]
@rncbc the PR wasn't complete, please have a look at the comments under it.

**Comment by rncbc** [comment]
@terencode: i have no special preference as long it works for you.

should i revert the merge?
