### ISSUE TITLE
Needs readme.md with instructions

### ISSUE THREAD

**Issue by mxa** [rncbc/rtirq#7]
I am missing a readme for rtirq.
Searching online for a manual gives me a couple of hits pointing to https://www.rncbc.org/jack#rtirq which isn't online any more.

**Comment by rncbc** [comment]
there's no readme nor ever was there any upstream, sorry. 
feel free to make up for one ;)
re. old dead link, it should be https://www.rncbc.org/archive/#rtirq, for years now.
thanks

**Comment by mxa** [comment]
https://github.com/rncbc/rtirq/pull/8

**Comment by mxa** [comment]
Thank you for merging. I'll fix some spelling and improve it in a couple of weeks when I have more time.
